#!/bin/sh

verbose=
board=
device=
dryrun=
imagedir=

get_defaults() {
	if [ -z "$board" -a -e /sys/firmware/devicetree/base/compatible ]; then
		case "$(cat /sys/firmware/devicetree/base/compatible 2>/dev/null)" in
		wand,*) board=wand ;;
		hardkernel,odroid-c2amlogic,*) board=odroid-c2 ;;
		esac
	fi

	if [ -z "$device" ]; then
		case "$board" in
		wand|cubie|cubie2) device=/dev/mmcblk0p0 ;;
		mx6cuboxi) device=/dev/mmcblk0 ;;
		odroid-c2) device=/dev/mmcblk0 ;;
		esac
	fi

	if [ -z "$imagedir" ]; then
		imagedir="$(realpath $(dirname $0))"
		[ -f "$imagedir/README.txt" ] || imagedir="/usr/share/u-boot"
	fi
}

die() {
	echo "ERROR: $@"
	exit 1
}

usage() {
	get_defaults

	cat <<EOF
usage: $0 [-b|--board <board-type>] [-d|--device <device>]

options:

 -b,--board <board>       Specify the board type: wand, cubie, cubie2, cuboxi, odroid-c2
                          (current default: ${board:-none})

 -d,--device <device>     Specify the device where to install u-boot
                          (current default: ${device:-none})

 -i,--imagedir <imagedir> Specify u-boot image directory
                          (current default: ${imagedir:-none})

 -n,--dry-run             Print commands but don't execute them

EOF
}

while [ $# -gt 0 ]; do
	opt="$1"
	shift
	case "$opt" in
	-b|--board)
		case "$1" in
		wand|wandboard) board="wand" ;;
		cubie|cubieboard) board="cubie" ;;
		cuboxi|mx6cuboxi) board="mx6cuboxi" ;;
		odroid-c2) board="odroid-c2" ;;
		*) usage; exit 1;;
		esac
		shift
		;;
	-d|--device)
		device="$1"
		shift
		;;
	-i|--imagedir)
		imagedir="$1"
		shift
		;;
	-n|--dry-run)
		dryrun="echo"
		;;
	--)
		break
		;;
	-*)
		usage
		exit 1
		;;
	esac
done

get_defaults
if [ -z "$board" -o -z "$device" -o -z "$imagedir" -o ! -e "$imagedir" ]; then
	usage
	exit 1
fi

if [ -z "$dryrun" ]; then
	echo "Updating $board u-boot in $device in 3 seconds..."
	sleep 3
fi

(
set -e
case "$board" in
wand)
	[ -e "$imagedir/wandboard" ] || die "wandboard images not installed, apk add u-boot-wandboard"
	$dryrun dd if="$imagedir"/wandboard/SPL of="$device" bs=1k seek=1 conv=notrunc status=none
	$dryrun dd if="$imagedir"/wandboard/u-boot.img of="$device" bs=1k seek=69 conv=notrunc status=none
	;;
cubie|cubie2)
	[ -e "$imagedir/Cubieboard${board#cubie}" ] || die "Cubieboard images not installed, apk add u-boot-cubieboard"
	$dryrun dd if="$imagedir"/Cubieboard"${board#cubie}"/u-boot-sunxi-with-spl.bin of="$device" bs=1024 seek=8 conv=notrunc status=none
	;;
mx6cuboxi)
	[ -e "$imagedir/mx6cuboxi" ] || die "iMX6 Cubox-i images not installed, apk add u-boot-cuboxi"
	$dryrun dd if="$imagedir"/mx6cuboxi/SPL of="$device" bs=1k seek=1 conv=notrunc status=none
	$dryrun dd if="$imagedir"/mx6cuboxi/u-boot.img of="$device" bs=1k seek=69 conv=notrunc status=none
	;;
odroid-c2)
	[ -e "$imagedir/odroid-c2" ] || die "ODROID-C2 images not installed, apk add u-boot-odroid"
	$dryrun dd if="$imagedir"/odroid-c2/bl1.bin.hardkernel of="$device" bs=1 count=442 conv=notrunc status=none
	$dryrun dd if="$imagedir"/odroid-c2/bl1.bin.hardkernel of="$device" bs=512 skip=1 seek=1 conv=notrunc status=none
	$dryrun dd if="$imagedir"/odroid-c2/u-boot.gxbb of="$device" bs=512 seek=97 conv=notrunc status=none
esac
$dryrun sync
) || die "U-Boot installation in $device failed"

[ -z "$dryrun" ] && echo "Completed successfully."
